spring:
  ai:
    openai:
      api-key: ${OPENAI_APIKEY}
      chat:
        options:
          temperature: 0
          model: gpt-4o-mini
#    openai:
#      api-key: ${GROQ_APIKEY}      
#      base-url: https://api.groq.com/openai
#      chat:
#        options:
#          model: llama-3.1-70b-versatile #gemma2-9b-it #mixtral-8x7b-32768 #llama3-groq-70b-8192-tool-use-preview #llama-3.1-70b-versatile #llama3-70b-8192
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true